import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/Card'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Linkly | Home - The Shorter The Better</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="h-full flex flex-col">
        {/* Hero */}
        <div className="flex flex-row h-full">
          {/* Left */}
          <div>
            <p>This is a small text</p> 
            <h1>This is a bigger text for linkly</h1>
            <p>This is yet another small text</p>
            <button>Start Here</button>
            <small>By registrying, you agree to our terms and conditions</small>
          </div>

          {/* Right */}
          <div>
            <Image src="/logo.png" alt="this is a header image" width="50px" height="50px" />
          </div>
        </div>
        {/* Services */}
        <div className="flex flex-row">
          {/* card */}
            <Card img="/logo.png" title="This is a card head" description="This is a description if the card"/>
            <Card img="/logo.png" title="This is a card head" description="This is a description if the card"/>
            <Card img="/logo.png" title="This is a card head" description="This is a description if the card"/>
            
        </div>
        {/* Statistics */}
        <div>

        </div>
        {/* Sign Up */}
        <div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
