import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Card from '../components/Card'


export default function Home() {
  return (
    <div className="h-full flex flex-col bg-blue-100">
      <Head>
        <title>Linkly | Home - The Shorter The Better</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <main className="h-full flex flex-col ">
        {/* Hero */}
        <div className="flex flex-row justify-between items-center h-screen bg-zinc-800 p-20">
          {/* Left */}
          <div>
            <p className="text-xl text-gray-400 mb-6">-Get your url short</p> 
            <h1 className="text-7xl text-white mb-16 font-bold">Enter your Link<br/>
            -We'll <span className="underline decoration-teal-500">
              shorten<span className="text-teal-500">.</span>it </span><br/> for you.</h1>
            
            <button 
                role="button"
                className="focus:ring-2 focus:ring-offset-2 focus:ring-teal-500 text-sm font-semibold leading-none text-white focus:outline-none bg-teal-500 border rounded hover:bg-teal-600 py-4 px-10 my-4 mb-4"
                disabled>
              Create an account
              </button><br/>
            <small className="text-gray-400">By signing up, I agree to shorten.it <span className="underline decoration-teal-500">Privacy Policy</span> and <span className="underline decoration-teal-500">Terms of Service</span></small>
          </div>

          {/* Right */}
          <div>
            <Image src="/phone1.png" width="650" height="500" alt="this is a header image" />
          </div>
        </div>
        {/* Services */}
        <div className="flex flex-col h-screen p-20">
          {/* card */}
          <div className ="flex">
            <h2 className="text-3xl font-medium m-10">What Are The Advantages Of Using Shorten.it</h2>
            <p className="m-10 text-gray-500">This url shortener platfprm has advantages that most other platforms do not have. Thi is intended so that user may feel comfortable using this platform</p>
          </div>
          <div className="flex">
          <Card img="/logo.png" title="Its free forever" description="This is a description if the card" />
            <Card img="/logo.png" title="This is a card head" description="This is a description if the card"/>
            <Card img="/logo.png" title="This is a card head" description="This is a description if the card"/>
          </div>
            
            
        </div>
        {/* Statistics */}
        <div>

        </div>
        {/* Sign Up */}
        <div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
